POST http://localhost:3001/api/persons/
Content-Type: application/json

{
   "name" : "Omoda",
   "number": "122223"
}

###
PUT http://localhost:3001/api/persons/65df8e38b9ea71d091a077a9
Content-Type: application/json

{
    "name": "olorun",
    "number": "908765"
}